# Generated by Django 4.2.3 on 2023-07-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(default="Easy", max_length=20),
        ),
    ]
