# Generated by Django 4.2.3 on 2023-07-05 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipeingredients", "0001_initial"),
        ("ingredients", "0001_initial"),
        ("recipes", "0004_recipe_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                through="recipeingredients.RecipeIngredient",
                to="ingredients.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(default="", max_length=20),
        ),
    ]
