# Generated by Django 4.2.3 on 2023-07-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_alter_recipe_difficulty"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="difficulty",
            field=models.CharField(
                blank=True, default="", editable=False, max_length=20
            ),
        ),
    ]
